// <auto-generated />
using DealManagement.Server.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DealManagement.Server.Migrations
{
    [DbContext(typeof(DealContext))]
    partial class DealContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DealManagement.Server.Domain.Models.Deal", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Slug");

                    b.ToTable("Deals");

                    b.HasData(
                        new
                        {
                            Slug = "summer-getaway",
                            Name = "Summer Getaway",
                            Video = "https://example.com/video1"
                        },
                        new
                        {
                            Slug = "winter-retreat",
                            Name = "Winter Retreat",
                            Video = "https://example.com/video2"
                        });
                });

            modelBuilder.Entity("DealManagement.Server.Domain.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DealSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(2,1)");

                    b.HasKey("Id");

                    b.HasIndex("DealSlug");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenities = "Pool,WiFi,Breakfast",
                            DealSlug = "summer-getaway",
                            Name = "Palm Beach Resort",
                            Rate = 4.5m
                        },
                        new
                        {
                            Id = 2,
                            Amenities = "WiFi,Parking,Gym",
                            DealSlug = "summer-getaway",
                            Name = "Oceanview Inn",
                            Rate = 4.2m
                        },
                        new
                        {
                            Id = 3,
                            Amenities = "Sauna,Fireplace,Bar",
                            DealSlug = "winter-retreat",
                            Name = "Snow Lodge",
                            Rate = 4.7m
                        });
                });

            modelBuilder.Entity("DealManagement.Server.Domain.Models.Hotel", b =>
                {
                    b.HasOne("DealManagement.Server.Domain.Models.Deal", "Deal")
                        .WithMany("Hotels")
                        .HasForeignKey("DealSlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("DealManagement.Server.Domain.Models.Deal", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
